default:
  golem_name: BioTrack
  golem_version: 0.0.0.9000
  app_prod: no
  path_db_specimen: !expr file.path('DB', 'dev', 'specimen')
  path_db_creds: !expr here::here("DB", "dev", "credentials.sqlite")
  log_version: Log Version 3.0 April 2022
production:
  app_prod: yes
  path_db_specimen: !expr file.path('DB', 'prod', 'specimen')
  path_db_creds: !expr here::here("DB", "prod", "credentials.sqlite")
dev:
  golem_wd: !expr here::here()
  path_db_specimen: !expr file.path('DB', 'dev', 'specimen')
  path_db_creds: !expr here::here("DB", "dev", "credentials.sqlite")
bococ:
  app_prod: yes
  golem_wd: !expr here::here()
  path_db_specimen: !expr file.path('DB', 'prod', 'specimen')
  path_db_creds: !expr here::here("DB", "prod", "credentials.sqlite")
